language: node_js
node_js:
  - '0.11'
  - '0.10'

notifications:
  flowdock:
    secure: "CwMVH1E+z1MhTqFJ33ft4PQ2dk2Bz3xMuu4CzZ7sT8e+TBuhMTbiBY+hK+yUuYIFHy5Objoe/3lnsx20w5U+C3PMv0WE20ulBJ5h03wOMbrpqPpmKITnFmZieWGxJuNStvAOCNbo/Fa98tGsb0I/4Sv4Ebj8z+9PWzg5sLAVWDs="
